COUNTRY_CODES = {
    "Afganistanas": "AF",
    "Albanija": "AL",
    "Alžyras": "DZ",
    "Andora": "AD",
    "Angola": "AO",
    "Antigva ir Barbuda": "AG",
    "Argentina": "AR",
    "Armėnija": "AM",
    "Australija": "AU",
    "Austrija": "AT",
    "Azerbaidžanas": "AZ",
    "Bahamai": "BS",
    "Bahreinas": "BH",
    "Bangladešas": "BD",
    "Barbadosas": "BB",
    "Baltarusija": "BY",
    "Belgija": "BE",
    "Belizas": "BZ",
    "Beninas": "BJ",
    "Bermuda": "BM",
    "Bocvano": "BW",
    "Bolivija": "BO",
    "Bosnija ir Hercegovina": "BA",
    "Brazilija": "BR",
    "Brunėjus": "BN",
    "Bulgarija": "BG",
    "Burkina Fasas": "BF",
    "Burundis": "BI",
    "Butanas": "BT",
    "Centrinės Afrikos Respublika": "CF",
    "Čadas": "TD",
    "Čekija": "CZ",
    "Čilė": "CL",
    "Danija": "DK",
    "Dominika": "DM",
    "Dominikos Respublika": "DO",
    "Džersis": "JE",
    "Džibutis": "DJ",
    "Egiptas": "EG",
    "Ekvadoras": "EC",
    "Ekvatorialinė Gvinėja": "GQ",
    "Eritrėja": "ER",
    "Estija": "EE",
    "Esvatini": "SZ",
    "Etiopija": "ET",
    "Falklando Salos": "FK",
    "Faroerų Salos": "FO",
    "Fidžis": "FJ",
    "Filipinai": "PH",
    "Gabonas": "GA",
    "Gajana": "GY",
    "Gambija": "GM",
    "Gana": "GH",
    "Gibraltaras": "GI",
    "Graikija": "GR",
    "Kipras": "CY",
    "Grenada": "GD",
    "Grenlandija": "GL",
    "Gruzija": "GE",
    "Guamas": "GU",
    "Gvajana": "GF",
    "Gvatemala": "GT",
    "Gvineja": "GN",
    "Gvinėja-Bisau": "GW",
    "Haitis": "HT",
    "Heard ir McDonaldo Salos": "HM",
    "Hondūras": "HN",
    "Indija": "IN",
    "Indonezija": "ID",
    "Irakas": "IQ",
    "Iranas": "IR",
    "Islandija": "IS",
    "Ispanija": "ES",
    "Italija": "IT",
    "Izraelis": "IL",
    "Jamaika": "JM",
    "Japonija": "JP",
    "Jemenas": "YE",
    "Jordanija": "JO",
    "Jungtiniai Arabų Emyratai": "AE",
    "Jungtinės Amerikos Valstijos": "US",
    "Jungtinės Karalystės Malaizija": "GB",
    "Jungtinės Karalystės Nyderlandai": "NL",
    "Jungtinės Karalystės Šiaurinės Marianaus Salos": "MP",
    "Jungtinės Karalystės Virginijos Salos": "VG",
    "Jungtinės Karalystės Virginijos Salos": "VI",
    "Juodkalnija": "ME",
    "Kaimanų Salos": "KY",
    "Kambodža": "KH",
    "Kamerūnas": "CM",
    "Kanada": "CA",
    "Kataras": "QA",
    "Kazachstanas": "KZ",
    "Kenija": "KE",
    "Kinija": "CN",
    "Kinijos Honkongo SAR": "HK",
    "Kinijos Makao SAR": "MO",
    "Kirgizija": "KG",
    "Kiribatis": "KI",
    "Kokosų Salos": "CC",
    "Kolumbija": "CO",
    "Komore": "KM",
    "Kongas": "CG",
    "Kosta Rika": "CR",
    "Kroatija": "HR",
    "Kuba": "CU",
    "Kuko Salos": "CK",
    "Kuveitas": "KW",
    "Laosas": "LA",
    "Latvija": "LV",
    "Lenkija": "PL",
    "Lesotas": "LS",
    "Libanas": "LB",
    "Liberija": "LR",
    "Libija": "LY",
    "Lichtenšteinas": "LI",
    "Lietuva": "LT",
    "Liuksemburgas": "LU",
    "Macao SAR": "MO",
    "Madagaskaras": "MG",
    "Makedonija": "MK",
    "Malavis": "MW",
    "Maldivai": "MV",
    "Malėzija": "MY",
    "Mali": "ML",
    "Malta": "MT",
    "Marokas": "MA",
    "Martinika": "MQ",
    "Mauricijus": "MU",
    "Mauritanija": "MR",
    "Meksika": "MX",
    "Mergelių Salos": "UM",
    "Mikronezija": "FM",
    "Moldova": "MD",
    "Monakas": "MC",
    "Mongolija": "MN",
    "Montseratas": "MS",
    "Mozambikas": "MZ",
    "Namibija": "NA",
    "Naujoji Kaledonija": "NC",
    "Naujoji Zelandija": "NZ",
    "Nauru": "NR",
    "Nepalas": "NP",
    "Nigerija": "NG",
    "Nigeris": "NE",
    "Nikaragva": "NI",
    "Niujė": "NU",
    "Norfolko Sala": "NF",
    "Norvegija": "NO",
    "Nyderlandai": "NL",
    "Olandija": "NL",
    "Omanas": "OM",
    "Pakistanas": "PK",
    "Palau": "PW",
    "Panama": "PA",
    "Papua Naujoji Gvinėja": "PG",
    "Paragvajus": "PY",
    "Peru": "PE",
    "Pietų Afrika": "ZA",
    "Pietų Džordžija ir Pietų Sandvičo Salos": "GS",
    "Pietų Korėja": "KR",
    "Pietų Sudanas": "SS",
    "Pitkerno Salos": "PN",
    "Portugalija": "PT",
    "Prancūzija": "FR",
    "Prancūzijos Gviana": "GF",
    "Prancūzijos Pietų ir Antarkties sritys": "TF",
    "Prancūzijos Polinezija": "PF",
    "Prancūzijos Sveti Pierre ir Miquelon": "PM",
    "Pusiaujo Naujoji Gvinėja": "PG",
    "Ruanda": "RW",
    "Rumunija": "RO",
    "Rusija": "RU",
    "Rytų Timoras": "TL",
    "Saliamono Salos": "SB",
    "Salvadoras": "SV",
    "Samoa": "WS",
    "San Marinas": "SM",
    "San Tomė ir Prinsipė": "ST",
    "Saudo Arabija": "SA",
    "Sen Pjeras ir Mikelonas": "PM",
    "Senegalas": "SN",
    "Sent Kitsas ir Nevis": "KN",
    "Serbija": "RS",
    "Serbija ir Juodkalnija": "CS",
    "Siera Leonė": "SL",
    "Singapūras": "SG",
    "Sirija": "SY",
    "Slovakija": "SK",
    "Slovėnija": "SI",
    "Somalis": "SO",
    "Somalis": "SO",
    "Sudanas": "SD",
    "Suomija": "FI",
    "Surinamas": "SR",
    "Svalbardo ir Jan Majeno Sala": "SJ",
    "Svazilandas": "SZ",
    "Šiaurės Korėja": "KP",
    "Šiaurės Marijanos": "MP",
    "Šiaurės Maris": "RU",
    "Šiaurės Sudanas": "SD",
    "Šri Lanka": "LK",
    "Šv. Vincentas ir Grenadinai": "VC",
    "Švedija": "SE",
    "Šveicarija": "CH",
    "Tadžikistanas": "TJ",
    "Tailandas": "TH",
    "Taiwanis": "TW",
    "Tanzanija": "TZ",
    "Togas": "TG",
    "Tokelau": "TK",
    "Tonga": "TO",
    "Trinidadas ir Tobagas": "TT",
    "Tunisas": "TN",
    "Turkija": "TR",
    "Turkmenistanas": "TM",
    "Turkso ir Caicoso Salos": "TC",
    "Tuvalu": "TV",
    "Uganda": "UG",
    "Ukraina": "UA",
    "Urugvajus": "UY",
    "Uzbekistanas": "UZ",
    "Vanuatu": "VU",
    "Vatikanas": "VA",
    "Venesuela": "VE",
    "Vengrija": "HU",
    "Vietnamas": "VN",
    "Vokietija": "DE",
    "Wallisas ir Futūna": "WF",
}